# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luvers_app.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 100, 191, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rightAllCheck = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightAllCheck.sizePolicy().hasHeightForWidth())
        self.rightAllCheck.setSizePolicy(sizePolicy)
        self.rightAllCheck.setText("")
        self.rightAllCheck.setObjectName("rightAllCheck")
        self.gridLayout.addWidget(self.rightAllCheck, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.bottomAllCheck = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomAllCheck.sizePolicy().hasHeightForWidth())
        self.bottomAllCheck.setSizePolicy(sizePolicy)
        self.bottomAllCheck.setText("")
        self.bottomAllCheck.setObjectName("bottomAllCheck")
        self.gridLayout.addWidget(self.bottomAllCheck, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.leftAllCheck = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftAllCheck.sizePolicy().hasHeightForWidth())
        self.leftAllCheck.setSizePolicy(sizePolicy)
        self.leftAllCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leftAllCheck.setText("")
        self.leftAllCheck.setObjectName("leftAllCheck")
        self.gridLayout.addWidget(self.leftAllCheck, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.topAllCheck = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topAllCheck.sizePolicy().hasHeightForWidth())
        self.topAllCheck.setSizePolicy(sizePolicy)
        self.topAllCheck.setText("")
        self.topAllCheck.setObjectName("topAllCheck")
        self.gridLayout.addWidget(self.topAllCheck, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 189, 82))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.techLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.techLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.techLabel.setObjectName("techLabel")
        self.verticalLayout.addWidget(self.techLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stepLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.stepLabel.setObjectName("stepLabel")
        self.horizontalLayout.addWidget(self.stepLabel)
        self.stepInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepInput.sizePolicy().hasHeightForWidth())
        self.stepInput.setSizePolicy(sizePolicy)
        self.stepInput.setObjectName("stepInput")
        self.horizontalLayout.addWidget(self.stepInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.offsetLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.offsetLabel.setObjectName("offsetLabel")
        self.horizontalLayout_2.addWidget(self.offsetLabel)
        self.offsetInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetInput.sizePolicy().hasHeightForWidth())
        self.offsetInput.setSizePolicy(sizePolicy)
        self.offsetInput.setObjectName("offsetInput")
        self.horizontalLayout_2.addWidget(self.offsetInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(360, 390, 288, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnSaveFile = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveFile.sizePolicy().hasHeightForWidth())
        self.btnSaveFile.setSizePolicy(sizePolicy)
        self.btnSaveFile.setObjectName("btnSaveFile")
        self.horizontalLayout_5.addWidget(self.btnSaveFile)
        self.btnOpenFile = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenFile.sizePolicy().hasHeightForWidth())
        self.btnOpenFile.setSizePolicy(sizePolicy)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout_5.addWidget(self.btnOpenFile)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(210, 30, 192, 61))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.banerWidth = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banerWidth.sizePolicy().hasHeightForWidth())
        self.banerWidth.setSizePolicy(sizePolicy)
        self.banerWidth.setReadOnly(True)
        self.banerWidth.setObjectName("banerWidth")
        self.horizontalLayout_3.addWidget(self.banerWidth, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.banerHeight = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banerHeight.sizePolicy().hasHeightForWidth())
        self.banerHeight.setSizePolicy(sizePolicy)
        self.banerHeight.setReadOnly(True)
        self.banerHeight.setObjectName("banerHeight")
        self.horizontalLayout_4.addWidget(self.banerHeight, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.techLabel.setText(_translate("MainWindow", "Параметры в мм."))
        self.stepLabel.setText(_translate("MainWindow", "Шаг:"))
        self.offsetLabel.setText(_translate("MainWindow", "Отступ :"))
        self.btnSaveFile.setText(_translate("MainWindow", "Сохранить файл"))
        self.btnOpenFile.setText(_translate("MainWindow", "Загрузить файл"))
        self.label.setText(_translate("MainWindow", "Ширина:"))
        self.label_2.setText(_translate("MainWindow", "Высота:"))

