# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luvers_app.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 263)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stepInput = QtWidgets.QLineEdit(self.centralwidget)
        self.stepInput.setGeometry(QtCore.QRect(100, 30, 141, 24))
        self.stepInput.setObjectName("stepInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 24))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(21, 94, 225, 120))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.topAllCheck = QtWidgets.QCheckBox(self.frame)
        self.topAllCheck.setGeometry(QtCore.QRect(100, 5, 16, 20))
        self.topAllCheck.setText("")
        self.topAllCheck.setChecked(True)
        self.topAllCheck.setObjectName("topAllCheck")
        self.leftAllCheck = QtWidgets.QCheckBox(self.frame)
        self.leftAllCheck.setGeometry(QtCore.QRect(5, 50, 21, 20))
        self.leftAllCheck.setText("")
        self.leftAllCheck.setChecked(True)
        self.leftAllCheck.setObjectName("leftAllCheck")
        self.bottomAllCheck = QtWidgets.QCheckBox(self.frame)
        self.bottomAllCheck.setGeometry(QtCore.QRect(100, 95, 16, 20))
        self.bottomAllCheck.setText("")
        self.bottomAllCheck.setChecked(True)
        self.bottomAllCheck.setObjectName("bottomAllCheck")
        self.rightAllCheck = QtWidgets.QCheckBox(self.frame)
        self.rightAllCheck.setGeometry(QtCore.QRect(200, 50, 16, 20))
        self.rightAllCheck.setText("")
        self.rightAllCheck.setChecked(True)
        self.rightAllCheck.setObjectName("rightAllCheck")
        self.cornerCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.cornerCheck.setGeometry(QtCore.QRect(20, 60, 141, 24))
        self.cornerCheck.setObjectName("cornerCheck")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 15, 40, 3))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 4, 151, 21))
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(215, 15, 40, 3))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 15, 20, 210))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(245, 15, 20, 210))
        self.line_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 224, 245, 3))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.btnOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenFile.setGeometry(QtCore.QRect(260, 10, 150, 40))
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.btnSaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveFile.setGeometry(QtCore.QRect(260, 50, 150, 40))
        self.btnSaveFile.setObjectName("btnSaveFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Люверсы"))
        self.label.setText(_translate("MainWindow", "Шаг (мм):"))
        self.cornerCheck.setText(_translate("MainWindow", "Только по углам"))
        self.label_2.setText(_translate("MainWindow", "Расстоновка люверсов"))
        self.btnOpenFile.setText(_translate("MainWindow", "Открыть файл"))
        self.btnSaveFile.setText(_translate("MainWindow", "Сохранить файл"))


